#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
root="$cwd/../.."
repo_dir=$(mktemp -d -t flycontainerise.XXXXX)
mkdir -p "$repo_dir/build/distributions"
cp -a "$root/build/distributions/." "$repo_dir/build/distributions/"
cp "$root/Dockerfile" "$repo_dir/"

fly \
  --target ci \
  execute \
  --privileged \
  --config "$cwd/containerise.yml" \
  --input repo="$repo_dir"
