#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
root="$cwd/../.."
build_dir=$(mktemp -d -t flycontainerise.XXXXX)
cp -a "$root/build/." "$build_dir/"

fly \
  --target ci \
  execute \
  --privileged \
  --config "$cwd/containerise.yml" \
  --input build="$build_dir" \
  --input repo="$root"
