platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 11.0.14.1-jdk

inputs:
- name: repo

run:
  path: ./gradlew
  args: [test]

caches:
- path: ../../../root/.gradle
